//TODO: refactor template strings into their own JSON file.
module.exports = {
	"help": require('./help.js'),
	"clist": require('./clist.js'),
	// add back in next update
	//"giverole": require('./giverole.js'),
	"setprefix": require('./setprefix.js'),
	"youtube": require('./youtube.js'),
	"giphy": require('./giphy.js'),
	"urban": require('./urban.js'),
	"playing": require('./playing.js'),
	"coinflip": require('./coinflip.js'),
	"rps": require('./rps.js'),
	"8ball": require('./eightball.js'),
	"eightball": require('./eightball.js'),
	"bang": require('./bang.js'),
	"choose": require('./choose.js'),
	"better": require('./choose.js'),
	"twittersearch": require('./twittersearch.js'),
	"booksearch": require('./booksearch.js'),
	"slots": require('./slots.js'),
	"leaderboards": require('./leaderboards.js'),
	"leaderboard": require('./leaderboards.js'),
	"profile": require('./profile.js'),
	"reflex": require('./reflex.js'),
	"info": require('./info.js'),
	"restart": require('./restart.js'),
	"role": require('./role.js'),
	"move": require('./move.js'),
	"findgame": require('./findgame.js'),
	"ping": require('./ping.js'),
	"userinfo": require('./userinfo.js'),
	"raffle": require('./raffle.js'),
	"serverinfo": require('./serverinfo.js'),
	"avatar": require('./avatar.js'),
	"massmove": require('./massmove.js'),
	// "nokko" : require('./rainbows.js'),
	// "phantom" : require('./ghost.js'),
	// "toggle": require('./toggleEmbeds.js'),
	"resetprefix": require('./resetprefix.js'),
	"perms": require('./evaluatepermissions.js'),
	"permissions": require('./evaluatepermissions.js'),
	"commands": require('./clist.js'),
	"hex": require('./hex.js'),
	"botclean": require('./botclean.js'),
	"typerace": require('./typerace.js'),
	"typeracer": require('./typerace.js'),
	"scramble": require('./scramble.js'),
	"scrambler": require('./scramble.js'),
	"random": require('./random.js'),
	//"notify": require('./notify.js'),
	//"cancel_notify": require('./notify.js')['command']('cancel'),
	//"confirm_notify": require('./notify.js')['command']('confirm'),
	"antiinvite": require('./anti_invite.js'),
	"invite": require('./invite.js'),
	"support": require('./server.js'),
	"prune": require('./prune.js'),
	"clean": require('./prune.js'),
	"hexname": require('./hexname.js'),
	"patreon": require('./patreon.js')
};
