module.exports = [
  "The violence interferes around a bread!",
  "The turning future explodes outside a routed royal.",
  "A peculiar blackmail conducts a stare.",
  "The wild hires its framework.",
  "The representative purple entrances a reminder beneath a rude transcript.",
  "The identified upstairs machines our geology.",
  "The season renames the bursting foreigner over the matter.",
  "The tense air washes before each plotted teacher.",
  "Every disconnected carrot initializes the transparent vacuum.",
  "Her rarer amplifier recycles a cozy carpet.",
  "A warp wises a deliberate insistence near a roundabout.",
  "A story relates the road across the reflecting cluster.",
  "A varied campaign combats a prose.",
  "The unconscious charts the smoker.",
  "Another western minister antiques the lump.",
  "The transformation covers the operational flute.",
  "The unbiased fighter prosecutes past a soil.",
  "Whatever reformed tutor approves a behavior.",
  "The crisis attains the aged wine above the satire.",
  "The female mutters across the leaning quota.",
  "Whatever pot smells next to the hope.",
  "When will its upgrade intimate a correspondence?",
  "The hidden steam bushes an assault.",
  "The conservative trash cards the mythology.",
  "Our medium buss parts a glow past the smooth mathematician.",
  "The ecology waits for the faint march.",
  "Opposite the coverage gasps any lake.",
  "The welfare legend pats your newcomer.",
  "How does the dread needle rave beneath a trifle?",
  "The cathedral jokes beneath the criminal.",
  "The pulled student gossips underneath the concept.",
  "Beneath the bankrupt automobile quibbles an asserting case.",
  "A fashioned disguise lies beneath an environmental wartime.",
  "The jail walks in a highway!",
  "The retaining misprint manipulates the lengthy adviser.",
  "Another load dances with the alien.",
  "Within the style clogs the summary barrister.",
  "When can a disgust squash a rot?",
  "The enlightened vocal rules on top of the implied wheel.",
  "The porter belongs to the jelly beneath a horrifying gas.",
  "Can the territory drink the irony life?",
  "Our fooling guideline spins before the playground.",
  "How can an album punt with the cute journalist?",
  "Why won't a custom affect enter next to the shirt?",
  "How can a country circular address whatever mistake?",
  "The policeman ropes a solar fuller outside its sound.",
  "In the decent east stops a million sabotage.",
  "Our clock produces the marked metaphor.",
  "A defensive mortal blocks the assault glance.",
  "The geometry excepts her speaker."
];
